{
 "title": "iotproj",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "1dh Pieces Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mqtt_v1_action_mount", "legendFormat": "1dh Pieces Count" }
   ]
  },
  {
   "title": "2dh Pieces Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mqtt_v2_action_mount", "legendFormat": "2dh Pieces Count" }
   ]
  },
  {
   "title": "5dh Pieces Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mqtt_v3_action_mount", "legendFormat": "5dh Pieces Count" }
   ]
  },
  {
   "title": "10dh Pieces Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mqtt_v4_action_mount", "legendFormat": "10dh Pieces Count" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Evolution dans le temps",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk(200, mqtt_v1_action_mount)",
     "legendFormat": "1dh Pieces Count"
    },
    { "expr": "mqtt_v2_action_mount", "legendFormat": "2dh Pieces Count" },
    { "expr": "mqtt_v3_action_mount", "legendFormat": "5dh Pieces Count" },
    {
     "expr": "mqtt_v4_action_mount",
     "fieldConfig": {
      "defaults": {
       "thresholds": {
        "mode": "absolute",
        "steps": [
         { "color": "green" },
         { "color": "red", "value": 70 }
        ]
       }
      }
     },
     "legendFormat": "10dh Pieces Count"
    }
   ]
  }
 ]
}